--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MCPEAbdu77/BirthdaysPE
build-by-default: true
branches:
- main
projects:
  BirthdaysPE:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.0
...
