---
name: BirthdaysPE
version: 1.0.0
main: MCA7\BirthdaysPE\BirthdaysPE
api: 4.0.0
author: MCA7
website: https://www.github.com/MCPEAbdu77/BirthdaysPE

commands:
  birthday:
    description: main command
    aliases: [bp]
    permission: birthdayspe.command
    
permissions:
  birthdayspe.command:
    default: true
...
