---
name: BirthdaysPE
version: 1.0.0
main: EPT\BirthdaysPE\BirthdaysPE
api: 4.0.0

commands:
  birthday:
    description: main command
    aliases: [bp]
    permission: birthdayspe.command
    
permissions:
  birthdayspe.command:
    default: true
...
